network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      addresses:
       - 172.16.11.10/20
      dhcp4: no
      routes:
       - to: 0.0.0.0/0
         via: 172.16.11.1 # Default gateway
         table: 1000
       - to: 172.16.11.10
         via: 0.0.0.0
         scope: link
         table: 1000
      routing-policy:
        - from: 172.16.11.10
          table: 1000
